// ⚠️ TEMPORÁRIO — apostas extraídas da planilha de Apostas do mês (snapshot 2026-06-15).
// Usado só pelo importador (BetsImport.tsx). A versão final NÃO terá importador.
// Remover = apagar este arquivo + BetsImport.tsx e a linha <BetsImport/> no Bets.tsx.
export interface BetSeedRow {
  date: string;
  tipster: string;
  sport?: string; house?: string; provider?: string;
  team1?: string; team2?: string; market?: string; selection?: string;
  moment?: 'PRE' | 'LIVE';
  stakeReais: number;
  odds: number;
  result: 'TBD' | 'W' | 'L' | 'R' | 'HW' | 'HL' | 'CASHED';
  cashoutValue?: number;
}

export const BET_SEED: BetSeedRow[] = [
 {
  "date": "2026-06-07",
  "tipster": "LG",
  "stakeReais": 1164.96,
  "odds": 1.55,
  "result": "L",
  "sport": "F1",
  "house": "Pinnacle",
  "provider": "Pinnacle",
  "team1": "GP Monaco",
  "team2": "Corrida",
  "market": "H2H",
  "selection": "George Russell vs Oscar Piastri",
  "moment": "PRE"
 },
 {
  "date": "2026-06-07",
  "tipster": "LG",
  "stakeReais": 1500.0,
  "odds": 2.0,
  "result": "W",
  "sport": "F1",
  "house": "UP",
  "provider": "Estrela",
  "team1": "GP Monaco",
  "team2": "Corrida",
  "market": "Apostas no Grupo",
  "selection": "Alex Albon",
  "moment": "PRE"
 },
 {
  "date": "2026-06-07",
  "tipster": "Labres",
  "stakeReais": 1971.0,
  "odds": 1.85,
  "result": "W",
  "sport": "CS",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "FlyQuest",
  "team2": "paiN",
  "market": "ML",
  "selection": "paiN",
  "moment": "PRE"
 },
 {
  "date": "2026-06-07",
  "tipster": "Labres",
  "stakeReais": 2000.25,
  "odds": 2.86,
  "result": "W",
  "sport": "CS",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Monte",
  "team2": "Legacy",
  "market": "ML",
  "selection": "Monte",
  "moment": "PRE"
 },
 {
  "date": "2026-06-08",
  "tipster": "League Punter",
  "stakeReais": 1400.35,
  "odds": 5.41,
  "result": "L",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Anyone's Legend",
  "team2": "Bilibili",
  "market": "ML",
  "selection": "Anyone's Legend",
  "moment": "PRE"
 },
 {
  "date": "2026-06-08",
  "tipster": "League Punter",
  "stakeReais": 999.9,
  "odds": 3.03,
  "result": "L",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Leviatan",
  "team2": "paiN",
  "market": "ML",
  "selection": "Leviatan",
  "moment": "PRE"
 },
 {
  "date": "2026-06-09",
  "tipster": "Labres",
  "stakeReais": 1499.6,
  "odds": 2.17,
  "result": "L",
  "sport": "Valorant",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Global",
  "team2": "FULL SENSE",
  "market": "ML",
  "selection": "FULL SENSE",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Labres",
  "stakeReais": 2027.15,
  "odds": 1.8,
  "result": "L",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Liquid",
  "team2": "Cloud9",
  "market": "ML",
  "selection": "Cloud9",
  "moment": "PRE"
 },
 {
  "date": "2026-06-09",
  "tipster": "Labres",
  "stakeReais": 1527.0,
  "odds": 2.46,
  "result": "L",
  "sport": "CS",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Monte",
  "team2": "paiN",
  "market": "ML",
  "selection": "Map 2 - paiN",
  "moment": "PRE"
 },
 {
  "date": "2026-06-19",
  "tipster": "Guia",
  "stakeReais": 552.1,
  "odds": 10.0,
  "result": "TBD",
  "sport": "Futebol",
  "house": "FortuneJack",
  "provider": "Blaze",
  "team1": "Copa do Mundo",
  "team2": "Grupo C",
  "market": "CDM",
  "selection": "1º Marrocos 2º Brasil",
  "moment": "PRE"
 },
 {
  "date": "2026-06-19",
  "tipster": "Guia",
  "stakeReais": 200.0,
  "odds": 22.0,
  "result": "TBD",
  "sport": "Futebol",
  "house": "FortuneJack",
  "provider": "Blaze",
  "team1": "Copa do Mundo",
  "team2": "Dupla Grupo C Grupo F",
  "market": "CDM",
  "selection": "Dupla Marrocos e Japão",
  "moment": "PRE"
 },
 {
  "date": "2026-06-10",
  "tipster": "Labres",
  "stakeReais": 1501.5,
  "odds": 1.82,
  "result": "W",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Fluxo W7M",
  "team2": "LOUD",
  "market": "ML",
  "selection": "LOUD",
  "moment": "PRE"
 },
 {
  "date": "2026-06-30",
  "tipster": "Ninguem",
  "stakeReais": 605.23,
  "odds": 20.0,
  "result": "TBD",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Copa do Mundo",
  "team2": "Campeão",
  "market": "CDM",
  "selection": "Brasil",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Labres",
  "stakeReais": 1500.0,
  "odds": 2.19,
  "result": "L",
  "sport": "CS",
  "house": "Pinnacle",
  "provider": "Pinnacle",
  "team1": "MOUZ",
  "team2": "Legacy",
  "market": "ML",
  "selection": "Legacy",
  "moment": "PRE"
 },
 {
  "date": "2026-06-19",
  "tipster": "Guia",
  "stakeReais": 2000.0,
  "odds": 2.29,
  "result": "TBD",
  "sport": "Futebol",
  "house": "FortuneJack",
  "provider": "Blaze",
  "team1": "Copa do Mundo",
  "team2": "Perde Todas",
  "market": "CDM",
  "selection": "Haiti",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 2350.0,
  "odds": 1.62,
  "result": "TBD",
  "sport": "Futebol",
  "house": "Estrela",
  "provider": "Estrela",
  "team1": "Copa do Mundo",
  "team2": "Ganha nenhuma",
  "market": "CDM",
  "selection": "Nova Zelândia",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 504.1,
  "odds": 4.3,
  "result": "TBD",
  "sport": "Futebol",
  "house": "FortuneJack",
  "provider": "Blaze",
  "team1": "Copa do Mundo",
  "team2": "Perde Todas",
  "market": "CDM",
  "selection": "Nova Zelândia",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Ninguem",
  "stakeReais": 2241.0,
  "odds": 2.4,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Copa do Mundo",
  "team2": "México x África do Sul Canadá x Bósnia e Herzegovina",
  "market": "SuperOddBet",
  "selection": "O1.5",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Ninguem",
  "stakeReais": 1500.0,
  "odds": 2.52,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "México",
  "team2": "África do Sul",
  "market": "SuperOddBet",
  "selection": "Criada ML México ML Cantos México",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Arrudex",
  "stakeReais": 120.0,
  "odds": 103.98,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Arrudex",
  "stakeReais": 146.24,
  "odds": 5.45,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Arrudex",
  "stakeReais": 120.0,
  "odds": 38.95,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Arrudex",
  "stakeReais": 139.29,
  "odds": 11.95,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Ninguem",
  "stakeReais": 270.86,
  "odds": 43.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "México",
  "team2": "África do Sul",
  "market": "Criada",
  "selection": "Criada com 25% Anytime Julián Quinõnes ML México U3.5 Cartões U8 Cantos O7.5 Chutes África do Sul",
  "moment": "PRE"
 },
 {
  "date": "2026-06-11",
  "tipster": "Ninguem",
  "stakeReais": 100.0,
  "odds": 2.0,
  "result": "W",
  "sport": "Futebol",
  "house": "Bet365",
  "provider": "Bet365",
  "team1": "México",
  "team2": "África do Sul",
  "market": "Super Aumentada 365",
  "selection": "O0.5 México",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Ninguem",
  "stakeReais": 100.0,
  "odds": 625.35,
  "result": "TBD",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Multipla",
  "team2": "Bingo",
  "market": "CDM",
  "selection": "Bingo Pontuação",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "LG",
  "stakeReais": 500.0,
  "odds": 5.6,
  "result": "L",
  "sport": "F1",
  "house": "Aviao",
  "provider": "Estrela",
  "team1": "GP Catalunha",
  "team2": "Treino Livre I",
  "market": "Vencedor",
  "selection": "Oscar Piastri",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "LG",
  "stakeReais": 500.0,
  "odds": 1.85,
  "result": "W",
  "sport": "F1",
  "house": "UP",
  "provider": "Estrela",
  "team1": "GP Catalunha",
  "team2": "Treino Livre I",
  "market": "Top 3",
  "selection": "Oscar Piastri",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "LG",
  "stakeReais": 500.0,
  "odds": 4.5,
  "result": "L",
  "sport": "F1",
  "house": "Aviao",
  "provider": "Estrela",
  "team1": "GP Catalunha",
  "team2": "Corrida",
  "market": "Vence Pole e Corrida",
  "selection": "George Russell",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "LG",
  "stakeReais": 700.0,
  "odds": 1.65,
  "result": "W",
  "sport": "F1",
  "house": "Novibet",
  "provider": "Novibet",
  "team1": "GP Catalunha",
  "team2": "Corrida",
  "market": "Pontuar",
  "selection": "Pierre Gasly",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Arrudex",
  "stakeReais": 80.0,
  "odds": 54.78,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 10.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 5.22,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-20",
  "tipster": "Guia",
  "stakeReais": 45.99,
  "odds": 2.38,
  "result": "TBD",
  "sport": "Futebol",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Turquia",
  "team2": "Paraguai",
  "market": "ML",
  "selection": "Turquia",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 750.0,
  "odds": 2.35,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Canadá",
  "team2": "Bósnia e Herzegovina",
  "market": "SuperOddBet",
  "selection": "Criada O1.5 O.75 Cantos",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 729.18,
  "odds": 3.4,
  "result": "L",
  "sport": "CS",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Natus Vincere",
  "team2": "Legacy",
  "market": "ML",
  "selection": "Legacy",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "LG",
  "stakeReais": 500.0,
  "odds": 2.27,
  "result": "L",
  "sport": "F1",
  "house": "UP",
  "provider": "Estrela",
  "team1": "GP Catalunha",
  "team2": "Treino Livre II",
  "market": "ML",
  "selection": "Kimi Antonelli",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 49.76,
  "odds": 15.77,
  "result": "R",
  "sport": "Futebol",
  "house": "Ultra",
  "provider": "VBet",
  "team1": "Copa do Mundo",
  "team2": "Aumentada",
  "market": "CDM",
  "selection": "Campeões Vencerem",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 49.76,
  "odds": 15.77,
  "result": "R",
  "sport": "Futebol",
  "house": "Maxima",
  "provider": "VBet",
  "team1": "Copa do Mundo",
  "team2": "Aumentada",
  "market": "CDM",
  "selection": "Campeões Vencerem",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 1000.0,
  "odds": 8.75,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Canadá",
  "team2": "Bósnia e Herzegovina",
  "market": "Criada",
  "selection": "Criada com 25% U4.5 Cartões U4.5 Cantos HT ML Canadá",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Arrudex",
  "stakeReais": 300.0,
  "odds": 5.33,
  "result": "L",
  "sport": "Beisebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Labres",
  "stakeReais": 1499.55,
  "odds": 2.56,
  "result": "L",
  "sport": "CS",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Falcons",
  "team2": "BetBoom",
  "market": "Handicap",
  "selection": "-1.5 Falcons",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 1046.0,
  "odds": 1.9,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Canadá",
  "team2": "Bósnia e Herzegovina",
  "market": "SuperOddBet",
  "selection": "Próximo Gol Canadá",
  "moment": "LIVE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 592.14,
  "odds": 19.12,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "EUA",
  "team2": "Paraguai",
  "market": "Criada",
  "selection": "Criada com 25% O14.5 Desarmes EUA ML Paraguai U3.5 Cartões",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Anytonco",
  "stakeReais": 250.0,
  "odds": 6.9,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "Assistencia",
  "selection": "Orkun Kokcu",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Anytonco",
  "stakeReais": 125.0,
  "odds": 34.0,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "Anytime",
  "selection": "2+ Mohamed Toure",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 250.0,
  "odds": 13.95,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Bet365",
  "team1": "Dupla",
  "team2": "Anytime",
  "market": "Anytime",
  "selection": "Dupla Raphinha Mohamed Toure",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Anytonco",
  "stakeReais": 1750.0,
  "odds": 4.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Bet365",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "Anytime",
  "selection": "Mohamed Toure",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 750.0,
  "odds": 3.1,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Bet365",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Anytime",
  "selection": "Raphinha",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 250.0,
  "odds": 37.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Dupla",
  "team2": "Anytime",
  "market": "Anytime",
  "selection": "Dupla Orkun Kokcu Bruno Guimarães",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Anytonco",
  "stakeReais": 625.0,
  "odds": 5.0,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "Anytime",
  "selection": "Orkun Kokcu",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 875.0,
  "odds": 7.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "Betano",
  "team1": "Dupla",
  "team2": "Anytime",
  "market": "Anytime",
  "selection": "Bruno Guimarães",
  "moment": "PRE"
 },
 {
  "date": "2026-06-12",
  "tipster": "Ninguem",
  "stakeReais": 404.0,
  "odds": 2.55,
  "result": "L",
  "sport": "Vôlei",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Turquia",
  "team2": "França",
  "market": "SuperOddBet",
  "selection": "Criada ML França O3.5 Sets",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 2750.0,
  "odds": 2.3,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Catar",
  "team2": "Suiça",
  "market": "SuperOddBet",
  "selection": "Criada O1.5 Suiça O4.5 Cantos Suiça",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Ninguem",
  "stakeReais": 799.0,
  "odds": 2.57,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "SuperOddBet",
  "selection": "Score or Assist Arda Guler",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 1000.0,
  "odds": 3.65,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Haiti",
  "team2": "Escócia",
  "market": "SuperOddBet",
  "selection": "Criada ML SOT Escócia ML Escócia ML Cantos Escócia",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 3500.0,
  "odds": 2.22,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "SuperOddBet",
  "selection": "Criada O0.5 Brasil ML Cantos Brasil",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "League Punter",
  "stakeReais": 250.0,
  "odds": 10.0,
  "result": "L",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Gen.G",
  "team2": "KT Rolster",
  "market": "ML",
  "selection": "KT Rolster",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "League Punter",
  "stakeReais": 1000.0,
  "odds": 2.0,
  "result": "L",
  "sport": "LoL",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "Gen.G",
  "team2": "KT Rolster",
  "market": "Handicap",
  "selection": "+2.5 KT Rolster",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 23.97,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 8.93,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "LG",
  "stakeReais": 47.69,
  "odds": 2.63,
  "result": "L",
  "sport": "F1",
  "house": "PolyMarket",
  "provider": "PolyMarket",
  "team1": "GP Catalunha",
  "team2": "Corrida",
  "market": "Vencedor",
  "selection": "George Russell",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 800.0,
  "odds": 5.5,
  "result": "W",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Catar",
  "team2": "Suiça",
  "market": "Criada",
  "selection": "Criada com 25% U1.5 Cartões Suiça ML HT Suiça O8.5 SOT",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 26.63,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 29.05,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Props Labres",
  "stakeReais": 100.0,
  "odds": 16.0,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Catar",
  "team2": "Suiça",
  "market": "Criada",
  "selection": "Criada com 25% 2+ Faltas Cometidas Breel Embolo 2+ Desarmes Nico Elvedi O11.5 Desarmes Suiça",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 500.0,
  "odds": 3.3,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Copa do Mundo",
  "team2": "Multipla",
  "market": "SuperOddBet",
  "selection": "Multipla O1.5 Todos Jogos do Dia",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 201.63,
  "odds": 22.25,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Catar",
  "team2": "Suiça",
  "market": "Criada",
  "selection": "Criada com 25% O7.5 Chutes Catar O11.5 Desarmes Suiça O11.5 Faltas Suiça U8.5 Tiros de Meta Catar",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 2000.0,
  "odds": 7.3,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Criada",
  "selection": "Criada com 50% U3.5 Cantos Marrocos ML Brasil U5.5 Cartões",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Ninguem",
  "stakeReais": 440.37,
  "odds": 3.58,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Criada",
  "selection": "Criada com 50% U4.5 Cartões U2.5 Cartões Marrocos DC Cartões Brasil",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 625.0,
  "odds": 2.8,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Anytime",
  "selection": "Igor Thiago",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 500.0,
  "odds": 2.1,
  "result": "W",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Finalização",
  "selection": "U2.5 Igor Thiago",
  "moment": "PRE"
 },
 {
  "date": "2026-06-13",
  "tipster": "Anytonco",
  "stakeReais": 595.82,
  "odds": 2.25,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Brasil",
  "team2": "Marrocos",
  "market": "Finalização",
  "selection": "U2.5 Brahim Diaz",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Ninguem",
  "stakeReais": 1000.0,
  "odds": 5.44,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Austrália",
  "team2": "Turquia",
  "market": "Criada",
  "selection": "Criada com 25% U3.5 Cartões U8.5 Cantos O1.5",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Arrudex",
  "stakeReais": 120.0,
  "odds": 0,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Arrudex",
  "stakeReais": 200.0,
  "odds": 43.95,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Arrudex",
  "stakeReais": 705.96,
  "odds": 2.82,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Alemanha",
  "team2": "Curaçao",
  "market": "Finalização",
  "selection": "U22.5 Alemanha",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "NHLTonco",
  "stakeReais": 40.0,
  "odds": 17.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "CAR Hurricanes",
  "team2": "VGS Golden Knights",
  "market": "Anytime",
  "selection": "Brayden McNabb",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "NHLTonco",
  "stakeReais": 100.0,
  "odds": 3.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "CAR Hurricanes",
  "team2": "VGS Golden Knights",
  "market": "Anytime",
  "selection": "Seth Jarvis",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "NHLTonco",
  "stakeReais": 82.73,
  "odds": 17.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "CAR Hurricanes",
  "team2": "VGS Golden Knights",
  "market": "Anytime",
  "selection": "William Carrier",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Arrudex",
  "stakeReais": 120.0,
  "odds": 57.73,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-14",
  "tipster": "Arrudex",
  "stakeReais": 333.6,
  "odds": 10.93,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 660.0,
  "odds": 1.95,
  "result": "W",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "SuperBet",
  "team1": "Espanha",
  "team2": "Cabo Verde",
  "market": "SuperOddBet",
  "selection": "O0.5 Cantos Espanha 10min",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 392.0,
  "odds": 3.4,
  "result": "W",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "SuperBet",
  "team1": "Espanha",
  "team2": "Cabo Verde",
  "market": "SuperOddBet",
  "selection": "O9.5 Cantos Espanha",
  "moment": "LIVE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 1000.0,
  "odds": 5.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Ellen",
  "provider": "Betano",
  "team1": "Espanha",
  "team2": "Cabo Verde",
  "market": "Criada",
  "selection": "Criada com 25% Anytime Pedri -1.5 Espanha",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Arrudex",
  "stakeReais": 333.46,
  "odds": 8.54,
  "result": "TBD",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Multipla",
  "team2": "Multipla",
  "market": "Multipla",
  "selection": "Estatísticas",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 750.0,
  "odds": 4.58,
  "result": "L",
  "sport": "Futebol",
  "house": "Bet365",
  "provider": "Bet365",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "Criada",
  "selection": "Criada Federico Valverde 1+ SOT, Falta Sofrida e Falta Cometida",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 477.28,
  "odds": 3.75,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "Faltas Cometidas",
  "selection": "O1.5 Federico Valverde",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 131.25,
  "odds": 11.0,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Bet365",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "Faltas Cometidas",
  "selection": "O2.5 Federico Valverde",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 500.0,
  "odds": 3.55,
  "result": "L",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "SuperBet",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "SuperOddBet",
  "selection": "Criada 1+ SOT Darwin Nunez 1+ SOT Federico Valverde ML Uruguai",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 400.0,
  "odds": 23.5,
  "result": "L",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "Criada",
  "selection": "Criada 25% U4.5 Cartões Anytime Federico Valverde U5.5 Tiros de Meta Uruguai",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 1000.0,
  "odds": 1.62,
  "result": "W",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "Cartões",
  "selection": "U4.5",
  "moment": "PRE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 1082.0,
  "odds": 1.87,
  "result": "W",
  "sport": "Futebol",
  "house": "Greg",
  "provider": "SuperBet",
  "team1": "Arábia Saudita",
  "team2": "Uruguai",
  "market": "SuperOddBet",
  "selection": "Próximo Gol Uruguai",
  "moment": "LIVE"
 },
 {
  "date": "2026-06-15",
  "tipster": "Ninguem",
  "stakeReais": 848.45,
  "odds": 9.75,
  "result": "TBD",
  "sport": "Futebol",
  "house": "Igor",
  "provider": "Betano",
  "team1": "Irã",
  "team2": "Nova Zelândia",
  "market": "Criada",
  "selection": "Criada 25% U3.5 Cartões DC Cartões Irã 2+ Chutes McCowatt",
  "moment": "PRE"
 }
];

// Unidade sugerida por tipster (da aba de unidades; editável no importador)
export const TIPSTER_UNIT_SUGGESTIONS: Record<string, number> = {
 "Anytonco": 1000.0,
 "Arrudex": 800.0,
 "Guia": 1000.0,
 "LG": 1000.0,
 "Labres": 1500.0,
 "League Punter": 1000.0,
 "NHLTonco": 1000.0,
 "Ninguem": 1000.0,
 "Props Labres": 1000.0
};
